### ISSUE TITLE
Correct stage deployment heroku 

### ISSUE THREAD

**Issue by luistelmocosta** [luistelmocosta/LDSO-FEUP#9]
`2016-12-06T00:44:42.098268+00:00 heroku[router]: at=info method=GET path="/login?next=%2Fhome" host=polexorg-stage.herokuapp.com request_id=60a63370-8ae3-4966-8a03-ca15ddb6e7d7 fwd="94.61.96.87" dyno=web.1 connect=0ms service=4ms status=200 bytes=6040
2016-12-06T00:44:54.509925+00:00 heroku[router]: at=info method=GET path="/home" host=polexorg-stage.herokuapp.com request_id=dcccf8a3-7b31-4295-acfa-cb06cae9aa7a fwd="94.61.96.87" dyno=web.1 connect=0ms service=7ms status=302 bytes=935
2016-12-06T00:44:54.662897+00:00 heroku[router]: at=info method=GET path="/login?next=%2Fhome" host=polexorg-stage.herokuapp.com request_id=4ae76e86-486b-4524-98f6-47dfe43465ef fwd="94.61.96.87" dyno=web.1 connect=0ms service=24ms status=200 bytes=5713
2016-12-06T01:21:13.379254+00:00 heroku[web.1]: Idling
2016-12-06T01:21:13.379877+00:00 heroku[web.1]: State changed from up to down
2016-12-06T01:21:14.152684+00:00 app[web.1]: [2016-12-06 01:21:14 +0000] [12] [INFO] Worker exiting (pid: 12)
2016-12-06T01:21:14.153211+00:00 app[web.1]: [2016-12-06 01:21:14 +0000] [13] [INFO] Worker exiting (pid: 13)
2016-12-06T01:21:14.153422+00:00 app[web.1]: [2016-12-06 01:21:14 +0000] [4] [INFO] Handling signal: term
2016-12-06T01:21:14.161147+00:00 app[web.1]: [2016-12-06 01:21:14 +0000] [4] [INFO] Shutting down: Master
2016-12-06T01:21:14.140964+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-12-06T01:21:14.315024+00:00 heroku[web.1]: Process exited with status 0
2016-12-07T10:41:59.400001+00:00 heroku[web.1]: Unidling
2016-12-07T10:41:59.400234+00:00 heroku[web.1]: State changed from down to starting
2016-12-07T10:42:04.548263+00:00 heroku[web.1]: Starting process with command `gunicorn run:app --preload`
2016-12-07T10:42:08.306007+00:00 heroku[web.1]: State changed from starting to up
2016-12-07T10:42:08.251726+00:00 app[web.1]: [2016-12-07 10:42:08 +0000] [4] [INFO] Starting gunicorn 19.6.0
2016-12-07T10:42:08.252292+00:00 app[web.1]: [2016-12-07 10:42:08 +0000] [4] [INFO] Listening at: http://0.0.0.0:20730 (4)
2016-12-07T10:42:08.256702+00:00 app[web.1]: [2016-12-07 10:42:08 +0000] [12] [INFO] Booting worker with pid: 12
2016-12-07T10:42:08.252369+00:00 app[web.1]: [2016-12-07 10:42:08 +0000] [4] [INFO] Using worker: sync
2016-12-07T10:42:08.317849+00:00 app[web.1]: [2016-12-07 10:42:08 +0000] [13] [INFO] Booting worker with pid: 13
2016-12-07T10:42:09.647836+00:00 heroku[router]: at=info method=GET path="/" host=polexorg-stage.herokuapp.com request_id=2bcf2f14-468d-4dce-be18-e054bb6d0bcc fwd="193.136.33.115" dyno=web.1 connect=0ms service=160ms status=200 bytes=1675
2016-12-07T10:43:08.866949+00:00 heroku[router]: at=info method=GET path="/" host=polexorg-stage.herokuapp.com request_id=0180ad23-27e0-4012-8ece-8ea75368a26a fwd="193.136.33.115" dyno=web.1 connect=1ms service=12ms status=200 bytes=1675
2016-12-07T10:43:09.075582+00:00 heroku[router]: at=info method=GET path="/static/css/landing-page.css" host=polexorg-stage.herokuapp.com request_id=547ac6a7-bba8-4302-a7b6-30734c3fd654 fwd="193.136.33.115" dyno=web.1 connect=5ms service=49ms status=200 bytes=3040
2016-12-07T10:43:09.391206+00:00 heroku[router]: at=info method=GET path="/static/img/assembleia.jpg" host=polexorg-stage.herokuapp.com request_id=0279c8c8-3a9b-4889-8f75-df8a35f84241 fwd="193.136.33.115" dyno=web.1 connect=0ms service=8ms status=200 bytes=150796
2016-12-07T10:43:09.609319+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=polexorg-stage.herokuapp.com request_id=859d4771-62af-424b-a5b3-d60ad79c05ee fwd="193.136.33.115" dyno=web.1 connect=0ms service=28ms status=404 bytes=508
2016-12-07T10:43:14.470946+00:00 heroku[router]: at=info method=GET path="/home" host=polexorg-stage.herokuapp.com request_id=aaa01e46-87c6-4a09-8eb0-419f8a2b7be8 fwd="193.136.33.115" dyno=web.1 connect=0ms service=103ms status=200 bytes=5637
2016-12-07T10:43:14.621412+00:00 heroku[router]: at=info method=GET path="/static/css/main.css" host=polexorg-stage.herokuapp.com request_id=81df6f78-333a-4e61-a48b-e17671fe4f89 fwd="193.136.33.115" dyno=web.1 connect=0ms service=3ms status=200 bytes=3557
2016-12-07T10:43:59.896421+00:00 heroku[router]: at=info method=GET path="/" host=polexorg-stage.herokuapp.com request_id=37ef251c-cc2c-4927-a4c8-da870110db08 fwd="193.136.33.110" dyno=web.1 connect=0ms service=2ms status=200 bytes=1553
2016-12-07T10:44:00.367868+00:00 heroku[router]: at=info method=GET path="/static/css/landing-page.css" host=polexorg-stage.herokuapp.com request_id=13b875ae-3051-4563-8602-f831abef24ed fwd="193.136.33.110" dyno=web.1 connect=0ms service=8ms status=200 bytes=2918
2016-12-07T10:44:00.864086+00:00 heroku[router]: at=info method=GET path="/static/img/assembleia.jpg" host=polexorg-stage.herokuapp.com request_id=daa3c657-87d5-4111-bb57-66709e6d0af1 fwd="193.136.33.110" dyno=web.1 connect=0ms service=7ms status=200 bytes=150674
2016-12-07T10:44:01.346234+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=polexorg-stage.herokuapp.com request_id=9ca3456b-019c-4a6b-a829-914a5a3f8400 fwd="193.136.33.110" dyno=web.1 connect=0ms service=2ms status=404 bytes=386
2016-12-07T10:44:02.789708+00:00 heroku[router]: at=info method=GET path="/home" host=polexorg-stage.herokuapp.com request_id=50d197a7-5603-4116-8d42-e782d2977df4 fwd="193.136.33.110" dyno=web.1 connect=0ms service=15ms status=302 bytes=661
2016-12-07T10:44:02.965364+00:00 heroku[router]: at=info method=GET path="/login?next=%2Fhome" host=polexorg-stage.herokuapp.com request_id=798a0a35-38bb-4a92-b13a-c3ee47aa924e fwd="193.136.33.110" dyno=web.1 connect=0ms service=23ms status=200 bytes=5535
2016-12-07T10:44:03.134781+00:00 heroku[router]: at=info method=GET path="/static/css/main.css" host=polexorg-stage.herokuapp.com request_id=31dea42f-c298-4ca5-9384-a8f77a8eedf5 fwd="193.136.33.110" dyno=web.1 connect=0ms service=3ms status=200 bytes=3637
2016-12-07T10:44:26.956360+00:00 heroku[router]: at=info method=POST path="/login?next=%2Fhome" host=polexorg-stage.herokuapp.com request_id=efca03c5-efd4-4df0-bd93-7e94a8fe054b fwd="193.136.33.110" dyno=web.1 connect=0ms service=28ms status=302 bytes=1129
2016-12-07T10:44:27.157346+00:00 heroku[router]: at=info method=GET path="/home" host=polexorg-stage.herokuapp.com request_id=69648232-9b39-4548-a5f2-7687385a7983 fwd="193.136.33.110" dyno=web.1 connect=0ms service=10ms status=200 bytes=6287
2016-12-07T10:44:42.105501+00:00 app[web.1]: <project.models.Politic object at 0x7f7283378190>
2016-12-07T10:44:42.109720+00:00 heroku[router]: at=info method=GET path="/politician/2" host=polexorg-stage.herokuapp.com request_id=e778526b-72c9-471e-94a0-347650d07148 fwd="193.136.33.110" dyno=web.1 connect=0ms service=16ms status=200 bytes=5724
2016-12-07T10:45:20.851280+00:00 heroku[router]: at=info method=GET path="/create_proposal/2" host=polexorg-stage.herokuapp.com request_id=c8b4a91e-ff6c-4a8e-a4c3-26d07f2b9c3f fwd="193.136.33.110" dyno=web.1 connect=4ms service=24ms status=200 bytes=6031
2016-12-07T10:45:37.056875+00:00 heroku[router]: at=info method=POST path="/create_proposal" host=polexorg-stage.herokuapp.com request_id=d4c7d213-0e9a-42d5-b650-1b254cc99b1a fwd="193.136.33.110" dyno=web.1 connect=0ms service=21ms status=500 bytes=244
2016-12-07T10:45:37.060241+00:00 app[web.1]: [2016-12-07 10:45:37 +0000] [13] [ERROR] Error handling request /create_proposal
2016-12-07T10:45:37.060255+00:00 app[web.1]: Traceback (most recent call last):
2016-12-07T10:45:37.060261+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
2016-12-07T10:45:37.060261+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2016-12-07T10:45:37.060262+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
2016-12-07T10:45:37.060263+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2016-12-07T10:45:37.060264+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
2016-12-07T10:45:37.060264+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2016-12-07T10:45:37.060265+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
2016-12-07T10:45:37.060266+00:00 app[web.1]:     response = self.make_response(self.handle_exception(e))
2016-12-07T10:45:37.060266+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
2016-12-07T10:45:37.060267+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-12-07T10:45:37.060268+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
2016-12-07T10:45:37.060268+00:00 app[web.1]:     response = self.full_dispatch_request()
2016-12-07T10:45:37.060269+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
2016-12-07T10:45:37.060270+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2016-12-07T10:45:37.060271+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
2016-12-07T10:45:37.060271+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2016-12-07T10:45:37.060272+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
2016-12-07T10:45:37.060272+00:00 app[web.1]:     rv = self.dispatch_request()
2016-12-07T10:45:37.060272+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
2016-12-07T10:45:37.060273+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2016-12-07T10:45:37.060273+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
2016-12-07T10:45:37.060274+00:00 app[web.1]:     return func(*args, **kwargs)
2016-12-07T10:45:37.060274+00:00 app[web.1]:   File "/app/project/proposals/views.py", line 37, in create_proposal
2016-12-07T10:45:37.060275+00:00 app[web.1]:     db.session.commit()
2016-12-07T10:45:37.060276+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 149, in do
2016-12-07T10:45:37.060276+00:00 app[web.1]:     return getattr(self.registry(), name)(*args, **kwargs)
2016-12-07T10:45:37.060276+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 765, in commit
2016-12-07T10:45:37.060277+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 370, in commit
2016-12-07T10:45:37.060277+00:00 app[web.1]:     self.transaction.commit()
2016-12-07T10:45:37.060278+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 350, in _prepare_impl
2016-12-07T10:45:37.060278+00:00 app[web.1]:     self.session.flush()
2016-12-07T10:45:37.060278+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1903, in flush
2016-12-07T10:45:37.060279+00:00 app[web.1]:     self._flush(objects)
2016-12-07T10:45:37.060279+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2021, in _flush
2016-12-07T10:45:37.060277+00:00 app[web.1]:     self._prepare_impl()
2016-12-07T10:45:37.060280+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 57, in __exit__
2016-12-07T10:45:37.060279+00:00 app[web.1]:     transaction.rollback(_capture_exception=True)
2016-12-07T10:45:37.060280+00:00 app[web.1]:     compat.reraise(exc_type, exc_value, exc_tb)
2016-12-07T10:45:37.060280+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1985, in _flush
2016-12-07T10:45:37.060280+00:00 app[web.1]:     flush_context.execute()
2016-12-07T10:45:37.060281+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 370, in execute
2016-12-07T10:45:37.060281+00:00 app[web.1]:     rec.execute(self)
2016-12-07T10:45:37.060281+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 479, in execute
2016-12-07T10:45:37.060282+00:00 app[web.1]:     self.dependency_processor.process_saves(uow, states)
2016-12-07T10:45:37.060283+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 1044, in process_saves
2016-12-07T10:45:37.060284+00:00 app[web.1]:     False, uowcommit, "add"):
2016-12-07T10:45:37.060284+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 1132, in _synchronize
2016-12-07T10:45:37.060285+00:00 app[web.1]:     self._verify_canload(child)
2016-12-07T10:45:37.060285+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/sqlalchemy/orm/dependency.py", line 252, in _verify_canload
2016-12-07T10:45:37.060285+00:00 app[web.1]:     "collection %s" % (self.prop, ))
2016-12-07T10:45:37.060286+00:00 app[web.1]: FlushError: Can't flush None value found in collection Proposal.children
2016-12-07T11:20:09.736077+00:00 heroku[web.1]: Idling
2016-12-07T11:20:09.736623+00:00 heroku[web.1]: State changed from up to down
2016-12-07T11:20:10.413779+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2016-12-07T11:20:10.425986+00:00 app[web.1]: [2016-12-07 11:20:10 +0000] [13] [INFO] Worker exiting (pid: 13)
2016-12-07T11:20:10.428431+00:00 app[web.1]: [2016-12-07 11:20:10 +0000] [12] [INFO] Worker exiting (pid: 12)
2016-12-07T11:20:10.433215+00:00 app[web.1]: [2016-12-07 11:20:10 +0000] [4] [INFO] Handling signal: term
2016-12-07T11:20:10.440688+00:00 app[web.1]: [2016-12-07 11:20:10 +0000] [4] [INFO] Shutting down: Master
2016-12-07T11:20:10.574914+00:00 heroku[web.1]: Process exited with status 0
`

Fix this heroku deployment error

**Comment by luistelmocosta** [comment]
Issue solved. Schema correctly depolyed to Heroku
